--- 
title: "Worldwide Mobile App User Behavior"
author: "Ruopu Fan & Xiaoyi Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

With the rapid growth of smartphone industry,  global mobile application market is also expanding quickly in the latest decade. Mobile users now can access a variety of applications including the popular ones like `Social Networking`, `Games`, `Utilities`, etc. Due to the impact of COVID-19, people tend to use social media and other applications to connect through the internet even more, which results in a surge in downloading of apps and increasing user activity overall.

In this project, we will carry out analysis based on the [Worldwide Mobile App User Behavior Dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27459), published by Harvard Dataverse. This dataset is collected from a global mobile app usage survey with 10,208 responses. Questions cover from the respondents' app usage habits to demographic information. We will visualize the data and discuss our findings on the following questions:

- Can we observe any difference in price sensitivity and income distribution for users from different app stores (e.g. iOS vs Android)?

- What categories are more male-/female-dominated? What are some of the gender-neutral categories? How are they connected with the user's age, nationality, and educational background?

- For price-sensitive users and those who are not, what are the distributions of annual income? What makes them decide to download and make in-app purchases?

Analysis related to the above questions will be presented in the following chapters.

To access the codes and other details, please see our github repository at [MobileAppUsage](https://github.com/RuopuFan/MobileAppUsage).

Publication related to this dataset: S. L. Lim, P. J. Bentley, N. Kanakam, F. Ishikawa and S. Honiden, "Investigating Country Differences in Mobile App User Behavior and Challenges for Software Engineering," in IEEE Transactions on Software Engineering, vol. 41, no. 1, pp. 40-64, 1 Jan. 2015, doi: 10.1109/TSE.2014.2360674.
