<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Missing values | Worldwide Mobile App User Behavior</title>
  <meta name="description" content="Chapter 4 Missing values | Worldwide Mobile App User Behavior" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Missing values | Worldwide Mobile App User Behavior" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Missing values | Worldwide Mobile App User Behavior" />
  
  
  

<meta name="author" content="Ruopu Fan &amp; Xiaoyi Zhang" />


<meta name="date" content="2021-12-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-transformation.html"/>
<link rel="next" href="results.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MobileAppUsage</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="data-sources.html"><a href="data-sources.html"><i class="fa fa-check"></i><b>2</b> Data sources</a></li>
<li class="chapter" data-level="3" data-path="data-transformation.html"><a href="data-transformation.html"><i class="fa fa-check"></i><b>3</b> Data transformation</a></li>
<li class="chapter" data-level="4" data-path="missing-values.html"><a href="missing-values.html"><i class="fa fa-check"></i><b>4</b> Missing values</a>
<ul>
<li class="chapter" data-level="4.1" data-path="missing-values.html"><a href="missing-values.html#column-pattern"><i class="fa fa-check"></i><b>4.1</b> Column pattern</a></li>
<li class="chapter" data-level="4.2" data-path="missing-values.html"><a href="missing-values.html#value-patterns"><i class="fa fa-check"></i><b>4.2</b> Value patterns</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="missing-values.html"><a href="missing-values.html#missing-values-by-app-store"><i class="fa fa-check"></i><b>4.2.1</b> Missing values by app store</a></li>
<li class="chapter" data-level="4.2.2" data-path="missing-values.html"><a href="missing-values.html#missing-values-by-app-store-price-sensitivity"><i class="fa fa-check"></i><b>4.2.2</b> Missing values by app store &amp; price sensitivity</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="missing-values.html"><a href="missing-values.html#missing-values-by-variable"><i class="fa fa-check"></i><b>4.3</b> Missing values by variable</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>5</b> Results</a>
<ul>
<li class="chapter" data-level="5.1" data-path="results.html"><a href="results.html#analysis-1"><i class="fa fa-check"></i><b>5.1</b> Analysis 1</a></li>
<li class="chapter" data-level="5.2" data-path="results.html"><a href="results.html#analysis-2"><i class="fa fa-check"></i><b>5.2</b> Analysis 2</a></li>
<li class="chapter" data-level="5.3" data-path="results.html"><a href="results.html#analysis-3-price-sensitive-users"><i class="fa fa-check"></i><b>5.3</b> Analysis 3: Price-sensitive users</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="results.html"><a href="results.html#income-distribution"><i class="fa fa-check"></i><b>5.3.1</b> Income Distribution</a></li>
<li class="chapter" data-level="5.3.2" data-path="results.html"><a href="results.html#reasons-why-people-download-apps-they-spent-on"><i class="fa fa-check"></i><b>5.3.2</b> Reasons why people download apps they spent on</a></li>
<li class="chapter" data-level="5.3.3" data-path="results.html"><a href="results.html#why-did-people-pay"><i class="fa fa-check"></i><b>5.3.3</b> Why did people pay?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="interactive-component.html"><a href="interactive-component.html"><i class="fa fa-check"></i><b>6</b> Interactive component</a></li>
<li class="chapter" data-level="7" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>7</b> Conclusion</a>
<ul>
<li class="chapter" data-level="7.1" data-path="conclusion.html"><a href="conclusion.html#analysis-1-1"><i class="fa fa-check"></i><b>7.1</b> Analysis 1</a></li>
<li class="chapter" data-level="7.2" data-path="conclusion.html"><a href="conclusion.html#analysis-2-1"><i class="fa fa-check"></i><b>7.2</b> Analysis 2</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Worldwide Mobile App User Behavior</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="missing-values" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Missing values</h1>
<p>In this section, we will look at the patterns in missing data. We expect to have many missing values in this <code>Mobile App User Dataset</code> as the data are collected from a survey where respondents may skip questions that they prefer not to answer.</p>
<div id="column-pattern" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Column pattern</h2>
<pre><code>## PriceSensitive      Education       YearsEdu     Occupation         Gender 
##           7104           4892           4892           4892           4842 
##            Age    Nationality       AppStore 
##           4842           4842           2310</code></pre>
<p>Here, we define <code>PriceSensitive</code> as people who took price into consideration when choosing apps to download (those who chose <em>Price</em> in Q9). On the other hand, NAs in this column represent people who skipped the question or those who didn’t choose <em>Price</em> for the question. In addition to 7,104 missing values in <code>PriceSensitive</code>, 4,892 people didn’t reply to education, years of education and occupation, while 4,842 values are missing for gender, age and nationalities. It also shows that 2,310 people skipped the question of “which app store do you use?” in the survey.</p>
</div>
<div id="value-patterns" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Value patterns</h2>
<div id="missing-values-by-app-store" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Missing values by app store</h3>
<pre><code>## # A tibble: 11 x 7
##    AppStore        Gender   Age Nationality Education YearsEdu Occupation
##    &lt;fct&gt;            &lt;int&gt; &lt;int&gt;       &lt;int&gt;     &lt;int&gt;    &lt;int&gt;      &lt;int&gt;
##  1 iOS                106   106         106       113      113        113
##  2 Do not use apps     24    24          24        24       24         24
##  3 Blackberry          28    28          28        35       35         35
##  4 Android            167   167         167       181      181        181
##  5 Nokia              102   102         102       105      105        105
##  6 Samsung             76    76          76        80       80         80
##  7 Windows             23    23          23        23       23         23
##  8 None              1595  1595        1595      1595     1595       1595
##  9 Not sure           390   390         390       403      403        403
## 10 Other               21    21          21        23       23         23
## 11 &lt;NA&gt;              2310  2310        2310      2310     2310       2310</code></pre>
<p>When we group the data by different App stores, some missing data appear to be highly correlated: <code>Gender</code>, <code>Age</code> and <code>Nationality</code> share the same patterns of missing values, while <code>Education</code>, <code>YearsEdu</code> and <code>Occupation</code> have exact same numbers of NAs in each App store. This shows that respondents who didn’t answer education-related questions also skipped the one for occupation. People who prefer not to answer their genders and ages avoided answering nationalities too.</p>
<p><img src="finalproj_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>If we visualize missing values of <code>Education</code> by App store, we can see that the largest number of NAs in education appears in the group NA in App store. We should consider removing these NAs since they have little information for both variables.</p>
</div>
<div id="missing-values-by-app-store-price-sensitivity" class="section level3" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Missing values by app store &amp; price sensitivity</h3>
<pre><code>## # A tibble: 11 x 4
##    AppStore        num_appstore num_na pct_na
##    &lt;fct&gt;                  &lt;int&gt;  &lt;int&gt;  &lt;dbl&gt;
##  1 &lt;NA&gt;                    2310   2310   1   
##  2 None                    1653   1633   0.99
##  3 Do not use apps           76     67   0.88
##  4 Not sure                 737    608   0.82
##  5 Nokia                    830    438   0.53
##  6 Other                    150     78   0.52
##  7 Samsung                  722    357   0.49
##  8 Android                 2066    990   0.48
##  9 Windows                  162     72   0.44
## 10 iOS                     1169    428   0.37
## 11 Blackberry               333    123   0.37</code></pre>
<p><img src="finalproj_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>All people who skipped writing down their App stores have an NA in <code>PriceSensitive</code>. People using iOS (Apple Store) appear to have the smallest number of missing values for the price question, so they are the most price-sensitive. We can also see that Android/Google and Samsung market users have similar percentages of NAs.</p>
</div>
</div>
<div id="missing-values-by-variable" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Missing values by variable</h2>
<p><img src="finalproj_files/figure-html/unnamed-chunk-15-1.png" width="1152" /></p>
<p>The most obvious pattern is the complete case (no NA in any column), indicating that over 2,500 observations contain all the information we need. The second most frequent missing pattern appears in the <code>PriceSensitive</code> column. It is interesting that many people didn’t provide any of their personal information in the survey, as we can see from the third, fourth &amp; fifth patterns.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-transformation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="results.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/RuopuFan/MobileAppUsage/edit/main/04-missing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/RuopuFan/MobileAppUsage/blob/main/04-missing.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
